# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_collection_ui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# from PyQt5 import QtCore, QtGui, QtWidgets
from PySide6 import QtCore, QtGui, QtWidgets  #Use Pyside6 to be consistent with GUI



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 460)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.measure_btn = QtWidgets.QPushButton(self.centralwidget)
        self.measure_btn.setGeometry(QtCore.QRect(330, 160, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.measure_btn.setFont(font)
        self.measure_btn.setObjectName("measure_btn")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(70, 290, 231, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.continuous_btn = QtWidgets.QRadioButton(self.centralwidget)
        self.continuous_btn.setGeometry(QtCore.QRect(140, 120, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.continuous_btn.setFont(font)
        self.continuous_btn.setObjectName("continuous_btn")
        self.tare_btn = QtWidgets.QPushButton(self.centralwidget)
        self.tare_btn.setGeometry(QtCore.QRect(70, 220, 521, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tare_btn.setFont(font)
        self.tare_btn.setObjectName("tare_btn")
        self.line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit.setGeometry(QtCore.QRect(110, 20, 421, 31))
        self.line_edit.setObjectName("line_edit")
        self.ondemand_btn = QtWidgets.QRadioButton(self.centralwidget)
        self.ondemand_btn.setGeometry(QtCore.QRect(140, 170, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ondemand_btn.setFont(font)
        self.ondemand_btn.setObjectName("ondemand_btn")
        self.mode_label = QtWidgets.QLabel(self.centralwidget)
        self.mode_label.setGeometry(QtCore.QRect(80, 90, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mode_label.setFont(font)
        self.mode_label.setObjectName("mode_label")
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setGeometry(QtCore.QRect(40, 420, 71, 21))
        self.time_label.setText("")
        self.time_label.setObjectName("time_label")
        self.browse_btn = QtWidgets.QPushButton(self.centralwidget)
        self.browse_btn.setGeometry(QtCore.QRect(540, 20, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browse_btn.setFont(font)
        self.browse_btn.setObjectName("browse_btn")
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setGeometry(QtCore.QRect(360, 290, 231, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stop_btn.setFont(font)
        self.stop_btn.setObjectName("stop_btn")
        self.connection_label = QtWidgets.QLabel(self.centralwidget)
        self.connection_label.setGeometry(QtCore.QRect(510, 420, 131, 21))
        self.connection_label.setText("")
        self.connection_label.setObjectName("connection_label")
        self.file_path_label = QtWidgets.QLabel(self.centralwidget)
        self.file_path_label.setGeometry(QtCore.QRect(30, 20, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.file_path_label.setFont(font)
        self.file_path_label.setObjectName("file_path_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.measure_btn.setText(_translate("MainWindow", "Measure Now"))
        self.start_btn.setText(_translate("MainWindow", "Start Data Collection"))
        self.continuous_btn.setText(_translate("MainWindow", "Continuous"))
        self.tare_btn.setText(_translate("MainWindow", "Tare Sensors"))
        self.ondemand_btn.setText(_translate("MainWindow", "On-demand"))
        self.mode_label.setText(_translate("MainWindow", "Mode"))
        self.browse_btn.setText(_translate("MainWindow", "Browse"))
        self.stop_btn.setText(_translate("MainWindow", "Stop Data Collection"))
        self.file_path_label.setText(_translate("MainWindow", "File Path"))
